### ISSUE TITLE
Adding volume normalization or allow modification of model

### ISSUE THREAD

**Issue by OmarAshkar** [nlmixr2/nonmem2rx#134]
Hello,

I am exploring this tool and it works great! I am just asking as normally we are interesting in simulating concentration not direct amount, and importing from nonmem doesn't give the flexibility to modify the outputs. 

I am thinking of the possiblilities to workaround aside from converting the rxSolve to dataframe and divide compartments by volume.

Can I append something like `Cp = central/V` to rxUI? or maybe allow this option to be automatically turned on importing using `nonmem2rx()`?

Thanks a lot!

**Comment by mattfidler** [comment]
Hi @OmarAshkar 

You can add whatever you want to the model using model piping.  If your imported model is `mod` then you can add `cp <- central/V` to the model by:

```r
mod %>%
  model(Cp <- central/V, append=TRUE)
```

However, for me (and others) I typically model concentrations instead of amounts, but you don't always get to choose what the model is doing if you are importing a model. 

On the other hand, I don't often add secondary parameters like `AUC` to the system, these can be helpful to add as a derived variable.

I have a vignette that I wrote that shows how to use model piping to add derived parameters to your model. It may be a bit more helpful because you should be able to run the code and experiment with other derived parameters if you wish.

The vignette is here:

https://nlmixr2.github.io/nonmem2rx/articles/simulate-extra-items.html

If you are planning on attending PAGE, I will be presenting a poster on `nonmem2rx` and `babelmixr2` feel free to stop by and chat.

I also hope to be at ACoP, though I may not be discussing this topic there.

**Comment by mattfidler** [comment]
Also note this is not on CRAN yet, though I hope to have it on CRAN before PAGE 2023.
